"""Error codes for the Pi-compatible financial runtime."""

AGENT_DEADLINE_EXCEEDED = "AGENT_DEADLINE_EXCEEDED"
AGENT_CANCELLED = "AGENT_CANCELLED"
AGENT_MAX_TURNS_EXCEEDED = "AGENT_MAX_TURNS_EXCEEDED"
AGENT_MAX_TOOL_CALLS_EXCEEDED = "AGENT_MAX_TOOL_CALLS_EXCEEDED"
AGENT_TOOL_NOT_ALLOWED = "AGENT_TOOL_NOT_ALLOWED"
AGENT_TOOL_ARGUMENT_INVALID = "AGENT_TOOL_ARGUMENT_INVALID"
AGENT_TOOL_TIMEOUT = "AGENT_TOOL_TIMEOUT"
AGENT_MODEL_UNAVAILABLE = "AGENT_MODEL_UNAVAILABLE"
AGENT_OUTPUT_SCHEMA_INVALID = "AGENT_OUTPUT_SCHEMA_INVALID"
AGENT_CONTEXT_TOO_LARGE = "AGENT_CONTEXT_TOO_LARGE"
AGENT_INTERNAL_ERROR = "AGENT_INTERNAL_ERROR"

TERMINAL_AGENT_ERRORS = {
    AGENT_DEADLINE_EXCEEDED,
    AGENT_CANCELLED,
    AGENT_MAX_TURNS_EXCEEDED,
    AGENT_MAX_TOOL_CALLS_EXCEEDED,
    AGENT_MODEL_UNAVAILABLE,
    AGENT_OUTPUT_SCHEMA_INVALID,
    AGENT_CONTEXT_TOO_LARGE,
    AGENT_INTERNAL_ERROR,
}
