"""add stock master

Revision ID: 76fe066db8b1
Revises: 4b49004d01a6
Create Date: 2026-06-01 09:37:36.678189+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fe066db8b1'
down_revision: Union[str, None] = '4b49004d01a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_master',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'symbol', name='uq_stock_master_market_symbol')
    )
    op.create_index('idx_stock_master_market_exchange', 'stock_master', ['market', 'exchange'], unique=False)
    op.create_index('idx_stock_master_market_name', 'stock_master', ['market', 'name'], unique=False)
    op.create_index('idx_stock_master_market_symbol', 'stock_master', ['market', 'symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_master_market_symbol', table_name='stock_master')
    op.drop_index('idx_stock_master_market_name', table_name='stock_master')
    op.drop_index('idx_stock_master_market_exchange', table_name='stock_master')
    op.drop_table('stock_master')
    # ### end Alembic commands ###
